artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MihirIngole28/Text-Synthesis-and-Compression-Project/raw/main/SamsumDataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir:  artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE:  artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "valiation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path:  artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

